# Generated by Django 4.1.6 on 2023-04-05 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PdfApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfdocument',
            old_name='title',
            new_name='name',
        ),
    ]
